name: practise pipeline

on:
  workflow_dispatch:

env:
  well: kamcho?

jobs:
  my_first_job:
    name: my first job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v7.0.0
    - name: 1st task hello
      run: echo "hello ${{ vars.FIRST_NAME}} . $well?"
    - name: 2nd task list file
      run: ls -a



       
       
       
