name: practise pipeline

on:
  workflow_dispatch:
  push: 
  pull_request: 
    branches: 
    - main
  

# env:
#   well: kamcho?

jobs:
  terraform_init_plan:
    name: terraform init & plan
    runs-on: ubuntu-latest
    steps:
    - name: terraform setup
      uses: hashicorp/setup-terraform@v4
    - name: terraform checkout
      uses: actions/checkout@v7
    - name: terraform init
      run: terraform init
      working-directory: env/dev
    - name: terraform fmt
      run: terraform fmt
      working-directory: env/dev
    - uses: azure/login@v3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: terraform plan
      run: terraform plan
      working-directory: env/dev
      



       
       
       
